// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uusaoqcuaskpqvsyrndd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1c2FvcWN1YXNrcHF2c3lybmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTUwNDUsImV4cCI6MjA2NTU5MTA0NX0.hclgLIzKihocv1GQOoHRdT11PolOaxrOuzXAsdp8lRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);